# Generated by Django 6.0.3 on 2026-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logoimage',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
    ]
